services:
  - type: web
    name: tfm-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
